# Generated by Django 5.2.13 on 2026-05-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cases/'),
        ),
    ]
