# Generated by Django 5.2.13 on 2026-05-02 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0003_challenge_problem_alter_designcase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.AddField(
            model_name='designcase',
            name='applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designcase',
            name='days_left',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='designcase',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='designcase',
            name='is_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designcase',
            name='prize',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='designcase',
            name='progress_pct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='designcase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('progress', 'In Progress'), ('done', 'Completed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='designer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AddField(
            model_name='designer',
            name='role',
            field=models.CharField(default='UI/UX Designer', max_length=100),
        ),
        migrations.AlterField(
            model_name='designimage',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hubapp.designcase'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='hubapp.designcase'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hubapp.designcase'),
        ),
        migrations.AlterField(
            model_name='review',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hubapp.designcase'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddesign',
            unique_together={('user', 'design')},
        ),
    ]
