# Generated by Django 5.2.13 on 2026-05-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0004_delete_challenge_delete_problem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designer',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='designer',
            name='achievements',
            field=models.TextField(blank=True, help_text='Awards, certifications'),
        ),
        migrations.AddField(
            model_name='designer',
            name='education',
            field=models.TextField(blank=True, help_text='Degree, university, year'),
        ),
        migrations.AddField(
            model_name='designer',
            name='experience',
            field=models.TextField(blank=True, help_text='Previous jobs (one per line)'),
        ),
        migrations.AddField(
            model_name='designer',
            name='featured_case',
            field=models.ForeignKey(blank=True, help_text='Select one of your design cases to feature on your profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_for_designer', to='hubapp.designcase'),
        ),
        migrations.AddField(
            model_name='designer',
            name='location',
            field=models.CharField(blank=True, default='San Francisco, CA', max_length=100),
        ),
        migrations.AddField(
            model_name='designer',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
