# Generated by Django 5.2.13 on 2026-05-03 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0005_alter_designer_options_designer_achievements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figma_link', models.URLField(blank=True, help_text='Link to Figma design')),
                ('design_images', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('description', models.TextField(blank=True, help_text='Explain your design decisions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_data', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hubapp.designcase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('problem', 'user')},
            },
        ),
    ]
