# Generated by Django 5.2.13 on 2026-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0006_designsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero', 'Hero Section Image'), ('why_improve', 'Why – Improve Your Skills (image 79)'), ('why_solve', 'Why – Solve Real Problems (image 80)'), ('why_hired', 'Why – Get Hired (image 81)'), ('cta_left', 'CTA Banner – Left Image (image 83)'), ('cta_right', 'CTA Banner – Right Image (image 84)')], help_text='Which section this image belongs to', max_length=30, unique=True)),
                ('image', models.ImageField(help_text='Upload the image file', upload_to='site_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility (optional)', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['key'],
            },
        ),
    ]
