# Generated by Django 5.2.13 on 2026-05-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0007_siteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(default='Hire Designer', max_length=100)),
                ('designers', models.CharField(default='1+', help_text='e.g. 12,000+', max_length=20)),
                ('companies', models.CharField(default='850+', help_text='e.g. 850+', max_length=20)),
            ],
            options={
                'verbose_name': 'CTA Banner',
                'verbose_name_plural': 'CTA Banner',
            },
        ),
        migrations.CreateModel(
            name='WhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(help_text='Display order: 1, 2, 3')),
                ('title', models.CharField(max_length=100)),
                ('point1', models.CharField(max_length=200)),
                ('point2', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Illustration shown below the bullet points', null=True, upload_to='why/')),
            ],
            options={
                'verbose_name': 'Why Section Card',
                'verbose_name_plural': 'Why Section Cards',
                'ordering': ['step'],
            },
        ),
    ]
