# Generated by Django 5.2.13 on 2026-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0008_ctabanner_whysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='projects_count',
            field=models.PositiveIntegerField(default=0, help_text='Manual project count (overrides automatic count from DesignCase)'),
        ),
    ]
