# Generated by Django 5.2.13 on 2026-05-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0009_designer_projects_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(choices=[('green', 'green'), ('purple', 'purple'), ('blue', 'blue')], default='purple', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30)),
                ('footer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrendingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('badge_type', models.CharField(choices=[('hot', '🔥 HOT'), ('rising', '📈 Rising')], default='hot', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('reward', models.CharField(max_length=50)),
                ('designers_count', models.PositiveIntegerField(default=0)),
                ('closing_text', models.CharField(max_length=100)),
                ('closing_color', models.CharField(choices=[('red', 'red'), ('blue', 'blue')], default='red', max_length=10)),
                ('link', models.URLField(blank=True, help_text='Optional custom URL, else defaults to problem detail')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this trending challenge', null=True, upload_to='trending/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
