# Generated by Django 5.2.13 on 2026-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0010_marketplacestat_trendingchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcase',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Final Design Preview image (shown in the Overview tab)', null=True, upload_to='cases/previews/'),
        ),
    ]
