# Generated by Django 5.2.13 on 2026-05-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0011_designcase_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='company_description',
            field=models.TextField(blank=True, default='...'),
        ),
        migrations.AddField(
            model_name='designer',
            name='company_name',
            field=models.CharField(blank=True, default='Netbank', max_length=100),
        ),
        migrations.AddField(
            model_name='designer',
            name='deadline',
            field=models.CharField(blank=True, default='April 30, 2026', max_length=50),
        ),
        migrations.AddField(
            model_name='designer',
            name='platform',
            field=models.CharField(blank=True, default='Mobile+Web', max_length=100),
        ),
        migrations.AddField(
            model_name='designer',
            name='requirements',
            field=models.TextField(blank=True, help_text='One per line'),
        ),
        migrations.AddField(
            model_name='designer',
            name='submission_guidelines',
            field=models.TextField(blank=True, help_text='One per line'),
        ),
    ]
