# Generated by Django 5.2.13 on 2026-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0012_designer_company_description_designer_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='submission_guidelines',
        ),
        migrations.AddField(
            model_name='designcase',
            name='company_description',
            field=models.TextField(blank=True, default='Netbank is a leading digital banking platform focused on delivering modern, secure, and user-friendly financial services.'),
        ),
        migrations.AddField(
            model_name='designcase',
            name='company_name',
            field=models.CharField(blank=True, default='Netbank', max_length=100),
        ),
        migrations.AddField(
            model_name='designcase',
            name='deadline',
            field=models.CharField(blank=True, default='April 30, 2026', max_length=50),
        ),
        migrations.AddField(
            model_name='designcase',
            name='platform',
            field=models.CharField(blank=True, default='Mobile+Web', max_length=100),
        ),
        migrations.AddField(
            model_name='designcase',
            name='requirements',
            field=models.TextField(blank=True, help_text='Enter each requirement on a new line. They will be displayed as bullet points.'),
        ),
        migrations.AddField(
            model_name='designcase',
            name='submission_guidelines',
            field=models.TextField(blank=True, help_text='Enter each guideline on a new line. They will be displayed as bullet points.'),
        ),
    ]
