# Generated by Django 5.2.13 on 2026-05-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0013_remove_designer_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='availability',
            field=models.CharField(blank=True, default='Available for Hire, Quick Response, Open for Freelance/Full Time', max_length=100),
        ),
        migrations.AddField(
            model_name='designer',
            name='problems_saved',
            field=models.CharField(blank=True, default='48K+', max_length=20),
        ),
        migrations.AddField(
            model_name='designer',
            name='skills',
            field=models.TextField(blank=True, help_text="Comma-separated list of skills, e.g. 'UI/UX, Figma, Web App'"),
        ),
        migrations.AddField(
            model_name='designer',
            name='success_rate',
            field=models.PositiveIntegerField(default=99, help_text='Percentage, e.g. 99'),
        ),
        migrations.AddField(
            model_name='designer',
            name='worked_companies',
            field=models.CharField(blank=True, default='15+', max_length=20),
        ),
        migrations.AlterField(
            model_name='designer',
            name='achievements',
            field=models.TextField(blank=True, help_text="One achievement per line, e.g. 'Top Designer Award\nCompleted 25 Challenges'"),
        ),
    ]
