# Generated by Django 5.2.13 on 2026-05-07 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0014_designer_availability_designer_problems_saved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designsubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='change_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='impact_preview',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='improvements_made',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='hubapp.designsubmission'),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='designsubmission',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='designsubmission',
            unique_together={('problem', 'user', 'version')},
        ),
    ]
