# Generated by Django 5.2.13 on 2026-05-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubapp', '0016_designer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingchallenge',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hubapp.designcase'),
        ),
    ]
